export const ANTICOUNTERFEIT_TRANSACTIONS_TYPE_GROUP = 2001;

export const REGISTER_MANUFACTURER_TYPE = 201;
export const REGISTER_PRODUCT_TYPE = 202;
export const TRANSFER_PRODUCT_TYPE = 203;
export const RECEIVE_PRODUCT_TYPE = 204;